#ddev-generated
services:
  hub:
    image: selenium/hub:${SELENIUM_HUB_VERSION:-4.38.0}
    container_name: ddev-${DDEV_SITENAME}-hub
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    external_links:
      - web:${DDEV_SITENAME}.${DDEV_TLD}

  chromium:
    image: selenium/node-chromium:${SELENIUM_CHROMIUM_VERSION:-142.0}
    container_name: ddev-${DDEV_SITENAME}-chromium
    shm_size: ${CHROME_SHM_SIZE:-256M}
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    external_links:
      - web:${DDEV_SITENAME}.${DDEV_TLD}

