---
name: Send notifications

"on":
  - release
  - issues
  - issue_comment
  - watch
  - pull_request_target

permissions:
  contents: read

jobs:
  notification:
    uses: >-
      maikschneider/reusable-workflows/.github/workflows/notifications.yml@main
    secrets:
      teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
