base: 'https://xima-typo3-recordlist.ddev.site/'
dependencies:
  - bootstrap-package/full
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
  -
    title: German
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 1
websiteTitle: ''
